<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <PackageProjectUrl>https://github.com/frequency403/OpenSSH-GUI</PackageProjectUrl>
        <VersionPrefix>3.2.3</VersionPrefix>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>
    
    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>ProjectUrl</_Parameter1>
            <_Parameter2>$(PackageProjectUrl)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>
    
    <PropertyGroup>
<!--        This "warning" is intended - because we use dependencyinjection-->
        <NoWarn>AVLN3001</NoWarn>
    </PropertyGroup>
</Project>