//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSSH_GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsAndTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsAndTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenSSH_GUI.Resources.StringsAndTexts", typeof(StringsAndTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string AddKeyWindowAbortButtonToolTipText {
            get {
                return ResourceManager.GetString("AddKeyWindowAbortButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SSH key.
        /// </summary>
        public static string AddKeyWindowAddKeyButtonToolTipText {
            get {
                return ResourceManager.GetString("AddKeyWindowAddKeyButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename does already exist!.
        /// </summary>
        public static string AddKeyWindowFilenameError {
            get {
                return ResourceManager.GetString("AddKeyWindowFilenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitsize.
        /// </summary>
        public static string AddKeyWindowKeyBitSizeComboBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyBitSizeComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (email@example.com).
        /// </summary>
        public static string AddKeyWindowKeyCommentTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyCommentTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key filename.
        /// </summary>
        public static string AddKeyWindowKeyFileNameTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyFileNameTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytype.
        /// </summary>
        public static string AddKeyWindowKeyKeyTypeComboBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyKeyTypeComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password? (leave empty for none).
        /// </summary>
        public static string AddKeyWindowKeyPasswordTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyPasswordTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new SSH key.
        /// </summary>
        public static string AddKeyWindowTitle {
            get {
                return ResourceManager.GetString("AddKeyWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup {0} files.
        /// </summary>
        public static string ApplicationSettingsCleanupFiles {
            get {
                return ResourceManager.GetString("ApplicationSettingsCleanupFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear whole cache.
        /// </summary>
        public static string ApplicationSettingsClearWholeCache {
            get {
                return ResourceManager.GetString("ApplicationSettingsClearWholeCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string ApplicationSettingsFontSize {
            get {
                return ResourceManager.GetString("ApplicationSettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogLevel.
        /// </summary>
        public static string ApplicationSettingsLogLevel {
            get {
                return ResourceManager.GetString("ApplicationSettingsLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed with caution.
        /// </summary>
        public static string ApplicationSettingsProceedWithCaution {
            get {
                return ResourceManager.GetString("ApplicationSettingsProceedWithCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ApplicationSettingsTheme {
            get {
                return ResourceManager.GetString("ApplicationSettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ApplicationSettingsViewModelAreYouSure {
            get {
                return ResourceManager.GetString("ApplicationSettingsViewModelAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the correct phrase to continue.
        /// </summary>
        public static string ApplicationSettingsViewModelConfirmationError {
            get {
                return ResourceManager.GetString("ApplicationSettingsViewModelConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I aM sUrE.
        /// </summary>
        public static string ApplicationSettingsViewModelConfirmDialogConfirmValue {
            get {
                return ResourceManager.GetString("ApplicationSettingsViewModelConfirmDialogConfirmValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all files and directories in \n{0}!\n\nType &quot;{1}&quot; to confirm deletion.
        /// </summary>
        public static string ApplicationSettingsViewModelConfirmMessageBoxContent {
            get {
                return ResourceManager.GetString("ApplicationSettingsViewModelConfirmMessageBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup logs older than.
        /// </summary>
        public static string ApplicationSettingsWindowCleanupLogsOlderThan {
            get {
                return ResourceManager.GetString("ApplicationSettingsWindowCleanupLogsOlderThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettingsWindowTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add key to authorized_keys file of.
        /// </summary>
        public static string AuthorizedKeysAddKeyToFileOf {
            get {
                return ResourceManager.GetString("AuthorizedKeysAddKeyToFileOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content from.
        /// </summary>
        public static string AuthorizedKeysFileContentFrom {
            get {
                return ResourceManager.GetString("AuthorizedKeysFileContentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content from local machine.
        /// </summary>
        public static string AuthorizedKeysFileContentLocal {
            get {
                return ResourceManager.GetString("AuthorizedKeysFileContentLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and close.
        /// </summary>
        public static string CancelAndClose {
            get {
                return ResourceManager.GetString("CancelAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string ConnectToServerConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectToServerConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to server.
        /// </summary>
        public static string ConnectToServerDescription {
            get {
                return ResourceManager.GetString("ConnectToServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string ConnectToServerHostname {
            get {
                return ResourceManager.GetString("ConnectToServerHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ConnectToServerPassword {
            get {
                return ResourceManager.GetString("ConnectToServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preconfigured Connections.
        /// </summary>
        public static string ConnectToServerPreconfiguredConnections {
            get {
                return ResourceManager.GetString("ConnectToServerPreconfiguredConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to ssh://{0}@{1}.
        /// </summary>
        public static string ConnectToServerSshConnectionString {
            get {
                return ResourceManager.GetString("ConnectToServerSshConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        public static string ConnectToServerStatusBase {
            get {
                return ResourceManager.GetString("ConnectToServerStatusBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string ConnectToServerStatusFailed {
            get {
                return ResourceManager.GetString("ConnectToServerStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string ConnectToServerStatusSuccess {
            get {
                return ResourceManager.GetString("ConnectToServerStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string ConnectToServerStatusUnknown {
            get {
                return ResourceManager.GetString("ConnectToServerStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not yet tested.
        /// </summary>
        public static string ConnectToServerStatusUntested {
            get {
                return ResourceManager.GetString("ConnectToServerStatusUntested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ConnectToServerUsername {
            get {
                return ResourceManager.GetString("ConnectToServerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing hostname/ip, username or password!.
        /// </summary>
        public static string ConnectToServerValidationError {
            get {
                return ResourceManager.GetString("ConnectToServerValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept connection.
        /// </summary>
        public static string ConnectWindowAcceptConnection {
            get {
                return ResourceManager.GetString("ConnectWindowAcceptConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset values.
        /// </summary>
        public static string ConnectWindowResetValues {
            get {
                return ResourceManager.GetString("ConnectWindowResetValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string ConnectWindowTestConnection {
            get {
                return ResourceManager.GetString("ConnectWindowTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all keys.
        /// </summary>
        public static string ConnectWindowUseAllKeys {
            get {
                return ResourceManager.GetString("ConnectWindowUseAllKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use public key.
        /// </summary>
        public static string ConnectWindowUsePubKey {
            get {
                return ResourceManager.GetString("ConnectWindowUsePubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string EditAuthorizedKeysLocal {
            get {
                return ResourceManager.GetString("EditAuthorizedKeysLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string EditAuthorizedKeysServer {
            get {
                return ResourceManager.GetString("EditAuthorizedKeysServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string EditKnownHostsLocal {
            get {
                return ResourceManager.GetString("EditKnownHostsLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string EditKnownHostsRemote {
            get {
                return ResourceManager.GetString("EditKnownHostsRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept changes and write to file.
        /// </summary>
        public static string EditKnownHostsWindowConfirmButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowConfirmButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss and Close.
        /// </summary>
        public static string EditKnownHostsWindowDismissButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDismissButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark for deletion on save.
        /// </summary>
        public static string EditKnownHostsWindowMarkForDeletionButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowMarkForDeletionButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit known_hosts file.
        /// </summary>
        public static string EditKnownHostsWindowTitle {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string ExportWindowCopyToClipboardToolTipText {
            get {
                return ResourceManager.GetString("ExportWindowCopyToClipboardToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change format to the {0} format.
        /// </summary>
        public static string FileInfoWindowChangeFormatTo {
            get {
                return ResourceManager.GetString("FileInfoWindowChangeFormatTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeMe.
        /// </summary>
        public static string FileInfoWindowChangeMessage {
            get {
                return ResourceManager.GetString("FileInfoWindowChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string FileInfoWindowChangePassword {
            get {
                return ResourceManager.GetString("FileInfoWindowChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password of this key.
        /// </summary>
        public static string FileInfoWindowChangePasswordTooltip {
            get {
                return ResourceManager.GetString("FileInfoWindowChangePasswordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm File Overwrite.
        /// </summary>
        public static string FileInfoWindowConfirmFileOverwrite {
            get {
                return ResourceManager.GetString("FileInfoWindowConfirmFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        public static string FileInfoWindowCurrent {
            get {
                return ResourceManager.GetString("FileInfoWindowCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new filename.
        /// </summary>
        public static string FileInfoWindowEnterNewFilename {
            get {
                return ResourceManager.GetString("FileInfoWindowEnterNewFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password for key {0}.
        /// </summary>
        public static string FileInfoWindowEnterNewPassword {
            get {
                return ResourceManager.GetString("FileInfoWindowEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyfile {0} already exist. Do you want to overwrite it?.
        /// </summary>
        public static string FileInfoWindowFileAlreadyExists {
            get {
                return ResourceManager.GetString("FileInfoWindowFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename cannot be empty.
        /// </summary>
        public static string FileInfoWindowFilenameCannotBeEmpty {
            get {
                return ResourceManager.GetString("FileInfoWindowFilenameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} associated Files.
        /// </summary>
        public static string FileInfoWindowFoundAssociatedFiles {
            get {
                return ResourceManager.GetString("FileInfoWindowFoundAssociatedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyFormat.
        /// </summary>
        public static string FileInfoWindowKeyFormat {
            get {
                return ResourceManager.GetString("FileInfoWindowKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string FileInfoWindowPassword {
            get {
                return ResourceManager.GetString("FileInfoWindowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password copied to clipboard.
        /// </summary>
        public static string FileInfoWindowPasswordCopied {
            get {
                return ResourceManager.GetString("FileInfoWindowPasswordCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Format.
        /// </summary>
        public static string KeyFormatDescription {
            get {
                return ResourceManager.GetString("KeyFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password.
        /// </summary>
        public static string KeysForgetPassword {
            get {
                return ResourceManager.GetString("KeysForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string KeysShowPassword {
            get {
                return ResourceManager.GetString("KeysShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password of {0}.
        /// </summary>
        public static string KeysShowPasswordOf {
            get {
                return ResourceManager.GetString("KeysShowPasswordOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SSH key.
        /// </summary>
        public static string MainWindowAddKeyToolTip {
            get {
                return ResourceManager.GetString("MainWindowAddKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected on:.
        /// </summary>
        public static string MainWindowConnectionTooltipConnectedOn {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipConnectedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currenty disconnected. Right click to open connection menu to establish a connection.
        /// </summary>
        public static string MainWindowConnectionTooltipDisconnected {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server OS:.
        /// </summary>
        public static string MainWindowConnectionTooltipServerOs {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipServerOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string MainWindowConnectMenuConnect {
            get {
                return ResourceManager.GetString("MainWindowConnectMenuConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string MainWindowConnectMenuDisconnect {
            get {
                return ResourceManager.GetString("MainWindowConnectMenuDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to opposite format.
        /// </summary>
        public static string MainWindowConvertTooltip {
            get {
                return ResourceManager.GetString("MainWindowConvertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingCommentText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export / Delete.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingExportDeleteText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingExportDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingFingerprintText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingFingerprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytype.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingKeyTypeText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingKeyTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete key from disk.
        /// </summary>
        public static string MainWindowDataGridControlsDeleteKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsDeleteKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export private key.
        /// </summary>
        public static string MainWindowDataGridControlsExportPrivateKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsExportPrivateKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export public key.
        /// </summary>
        public static string MainWindowDataGridControlsExportPublicKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsExportPublicKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path:.
        /// </summary>
        public static string MainWindowDataGridRowDetailsAbsolutePathText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsAbsolutePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename on disk:.
        /// </summary>
        public static string MainWindowDataGridRowDetailsFilenameText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsFilenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to disconnect from!.
        /// </summary>
        public static string MainWindowDisconnectBoxTextNone {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTextNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected successfully!.
        /// </summary>
        public static string MainWindowDisconnectBoxTextSuccess {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from Server.
        /// </summary>
        public static string MainWindowDisconnectBoxTitle {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit authorized_keys.
        /// </summary>
        public static string MainWindowEditAuthorizedKeys {
            get {
                return ResourceManager.GetString("MainWindowEditAuthorizedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;known_hosts&quot; file.
        /// </summary>
        public static string MainWindowEditKnownHostsFileToolTip {
            get {
                return ResourceManager.GetString("MainWindowEditKnownHostsFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} keypairs in SSH directory.
        /// </summary>
        public static string MainWindowFoundKeyPairsCountLabel {
            get {
                return ResourceManager.GetString("MainWindowFoundKeyPairsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindowHelpMenuAbout {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question or for help.
        /// </summary>
        public static string MainWindowHelpMenuQuestion {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website/Manual.
        /// </summary>
        public static string MainWindowHelpMenuWebsite {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a server to edit the remote file!.
        /// </summary>
        public static string MainWindowIsNotRemoteTooltipText {
            get {
                return ResourceManager.GetString("MainWindowIsNotRemoteTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Format/Type:.
        /// </summary>
        public static string MainWindowKeyFormatType {
            get {
                return ResourceManager.GetString("MainWindowKeyFormatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is not password protected.
        /// </summary>
        public static string MainWindowKeyNotPasswordProtected {
            get {
                return ResourceManager.GetString("MainWindowKeyNotPasswordProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is password protected and cannot be used until a password is provided.
        /// </summary>
        public static string MainWindowKeyPasswordProtectedLocked {
            get {
                return ResourceManager.GetString("MainWindowKeyPasswordProtectedLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is password protected and opened with correct password.
        /// </summary>
        public static string MainWindowKeyPasswordProtectedUnlocked {
            get {
                return ResourceManager.GetString("MainWindowKeyPasswordProtectedUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Fileinfo Window.
        /// </summary>
        public static string MainWindowOpenFileInfoWindow {
            get {
                return ResourceManager.GetString("MainWindowOpenFileInfoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Password.
        /// </summary>
        public static string MainWindowProvidePassword {
            get {
                return ResourceManager.GetString("MainWindowProvidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading keys....
        /// </summary>
        public static string MainWindowReloadingKeys {
            get {
                return ResourceManager.GetString("MainWindowReloadingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click for help.
        /// </summary>
        public static string MainWindowRightClickHelp {
            get {
                return ResourceManager.GetString("MainWindowRightClickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click for options.
        /// </summary>
        public static string MainWindowRightClickOptions {
            get {
                return ResourceManager.GetString("MainWindowRightClickOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string MainWindowSettingsMenuAppSettings {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local user ssh config.
        /// </summary>
        public static string MainWindowSettingsMenuLocalUserSshConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuLocalUserSshConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine sshd config.
        /// </summary>
        public static string MainWindowSettingsMenuMachineSshdConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuMachineSshdConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload keys from disk.
        /// </summary>
        public static string MainWindowSettingsMenuReloadKeysFromDisk {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuReloadKeysFromDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote user ssh config.
        /// </summary>
        public static string MainWindowSettingsMenuRemoteMachineSshdConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuRemoteMachineSshdConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote machine sshd config.
        /// </summary>
        public static string MainWindowSettingsMenuRemoteUserSshConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuRemoteUserSshConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Filename.
        /// </summary>
        public static string MainWindowViewModelChangeFilename {
            get {
                return ResourceManager.GetString("MainWindowViewModelChangeFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change filename - file is referenced in configuration files.
        /// </summary>
        public static string MainWindowViewModelChangeFilenameDisabledTooltip {
            get {
                return ResourceManager.GetString("MainWindowViewModelChangeFilenameDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete the SSH keypair?.
        /// </summary>
        public static string MainWindowViewModelDeleteKeyQuestionTextPair {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyQuestionTextPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        public static string MainWindowViewModelDeleteKeyTitleText {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0} key: {1}.
        /// </summary>
        public static string MainWindowViewModelDynamicExportWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowViewModelDynamicExportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting keyfile!.
        /// </summary>
        public static string MainWindowViewModelExportKeyErrorMessage {
            get {
                return ResourceManager.GetString("MainWindowViewModelExportKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You provided a wrong password. Do you want to try again?.
        /// </summary>
        public static string MainWindowViewModelProvidePasswordErrorContent {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect!.
        /// </summary>
        public static string MainWindowViewModelProvidePasswordErrorHeading {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordErrorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide password for key.
        /// </summary>
        public static string MainWindowViewModelProvidePasswordPromptBodyHeading {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordPromptBodyHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password:.
        /// </summary>
        public static string MainWindowViewModelProvidePasswordPromptHeading {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordPromptHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function is not implemented yet, but planned!.
        /// </summary>
        public static string NotImplementedBoxText {
            get {
                return ResourceManager.GetString("NotImplementedBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet.
        /// </summary>
        public static string NotImplementedBoxTitle {
            get {
                return ResourceManager.GetString("NotImplementedBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes and close.
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
    }
}
