name: Build and Release

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build for Linux
        run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true OpenSSHA-GUI/OpenSSHA-GUI.csproj

      - name: Build for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true OpenSSHA-GUI/OpenSSHA-GUI.csproj

      - name: Build for macOS
        run: dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true OpenSSHA-GUI/OpenSSHA-GUI.csproj

      - name: SortFiles
        run: cp OpenSSHA-GUI/bin/Release/net8.0/linux-x64/publish/OpenSSHA-GUI OpenSSH-GUI-linux-x64.bin && cp OpenSSHA-GUI/bin/Release/net8.0/win-x64/publish/OpenSSHA-GUI.exe OpenSSH-GUI-win-x64.exe && cp OpenSSHA-GUI/bin/Release/net8.0/osx-x64/publish/OpenSSHA-GUI OpenSSH-GUI-osx-x64.bin

      - name: setup go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.1'

      - name: Create Release
        id: create_release
        uses: https://gitea.com/actions/release-action@main
        with:
          tag_name: ${{ gitea.ref }}
          release_name: Release ${{ gitea.ref }}
          draft: false
          prerelease: false
          api_key: ${{ secrets.TOKEN }}
          files: |-
            OpenSSH-GUI-linux-x64.bin
            OpenSSH-GUI-win-x64.exe
            OpenSSH-GUI-osx-x64.bin
