//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSSHA_GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsAndTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsAndTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenSSHA-GUI.StringsAndTexts", typeof(StringsAndTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string AddKeyWindowAbortButtonToolTipText {
            get {
                return ResourceManager.GetString("AddKeyWindowAbortButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SSH key.
        /// </summary>
        public static string AddKeyWindowAddKeyButtonToolTipText {
            get {
                return ResourceManager.GetString("AddKeyWindowAddKeyButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitsize.
        /// </summary>
        public static string AddKeyWindowKeyBitSizeComboBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyBitSizeComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (email@example.com).
        /// </summary>
        public static string AddKeyWindowKeyCommentTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyCommentTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key filename.
        /// </summary>
        public static string AddKeyWindowKeyFileNameTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyFileNameTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytype.
        /// </summary>
        public static string AddKeyWindowKeyKeyTypeComboBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyKeyTypeComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password? (leave empty for none).
        /// </summary>
        public static string AddKeyWindowKeyPasswordTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyPasswordTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new SSH key.
        /// </summary>
        public static string AddKeyWindowTitle {
            get {
                return ResourceManager.GetString("AddKeyWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ConfirmDialogDefaultNoText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ConfirmDialogDefaultOkText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allright?.
        /// </summary>
        public static string ConfirmDialogDefaultQuestionText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept changes and write to file.
        /// </summary>
        public static string EditKnownHostsWindowConfirmButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowConfirmButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        public static string EditKnownHostsWindowDataGridColumnHeaderFingerprintText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderFingerprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keysize.
        /// </summary>
        public static string EditKnownHostsWindowDataGridColumnHeaderKeySizeText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderKeySizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytype.
        /// </summary>
        public static string EditKnownHostsWindowDataGridColumnHeaderKeyTypeText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderKeyTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string EditKnownHostsWindowDataGridColumnHeaderOptionsText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss and Close.
        /// </summary>
        public static string EditKnownHostsWindowDismissButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDismissButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark for deletion on save.
        /// </summary>
        public static string EditKnownHostsWindowMarkForDeletionButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowMarkForDeletionButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload file and revert changes.
        /// </summary>
        public static string EditKnownHostsWindowReloadButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowReloadButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit known_hosts file.
        /// </summary>
        public static string EditKnownHostsWindowTitle {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string ExportWindowCopyToClipboardToolTipText {
            get {
                return ResourceManager.GetString("ExportWindowCopyToClipboardToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SSH key.
        /// </summary>
        public static string MainWindowAddKeyToolTip {
            get {
                return ResourceManager.GetString("MainWindowAddKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingCommentText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export / Delete.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingExportDeleteText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingExportDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingFingerprintText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingFingerprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keysize in bytes.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingKeySizeText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingKeySizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytype.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingKeyTypeText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingKeyTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete key from disk.
        /// </summary>
        public static string MainWindowDataGridControlsDeleteKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsDeleteKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export private key.
        /// </summary>
        public static string MainWindowDataGridControlsExportPrivateKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsExportPrivateKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export public key.
        /// </summary>
        public static string MainWindowDataGridControlsExportPublicKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsExportPublicKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path:.
        /// </summary>
        public static string MainWindowDataGridRowDetailsAbsolutePathText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsAbsolutePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename on disk:.
        /// </summary>
        public static string MainWindowDataGridRowDetailsFilenameText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsFilenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key filename:.
        /// </summary>
        public static string MainWindowDataGridRowDetailsPrivateKeyFilenameText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsPrivateKeyFilenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;known_hosts&quot; file.
        /// </summary>
        public static string MainWindowEditKnownHostsFileToolTip {
            get {
                return ResourceManager.GetString("MainWindowEditKnownHostsFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string MainWindowFoundKeyPairsCountLabelPart1 {
            get {
                return ResourceManager.GetString("MainWindowFoundKeyPairsCountLabelPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keypairs in SSH directory.
        /// </summary>
        public static string MainWindowFoundKeyPairsCountLabelPart2 {
            get {
                return ResourceManager.GetString("MainWindowFoundKeyPairsCountLabelPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSSH GUI.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete the SSH key?.
        /// </summary>
        public static string MainWindowViewModelDeleteKeyQuestionText {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} &amp; {1}?.
        /// </summary>
        public static string MainWindowViewModelDeleteKeyTitleText {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0} key: {1}.
        /// </summary>
        public static string MainWindowViewModelDynamicExportWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowViewModelDynamicExportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open or read keyfile!.
        /// </summary>
        public static string MainWindowViewModelExportKeyErrorMessage {
            get {
                return ResourceManager.GetString("MainWindowViewModelExportKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem loading &quot;{0}&quot;: {1}.
        /// </summary>
        public static string MainWindowViewModelProblemLoadingFileText {
            get {
                return ResourceManager.GetString("MainWindowViewModelProblemLoadingFileText", resourceCulture);
            }
        }
    }
}
