//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSSH_GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsAndTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsAndTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenSSH_GUI.StringsAndTexts", typeof(StringsAndTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string AddKeyWindowAbortButtonToolTipText {
            get {
                return ResourceManager.GetString("AddKeyWindowAbortButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SSH key.
        /// </summary>
        public static string AddKeyWindowAddKeyButtonToolTipText {
            get {
                return ResourceManager.GetString("AddKeyWindowAddKeyButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is default!.
        /// </summary>
        public static string AddKeyWindowDefault {
            get {
                return ResourceManager.GetString("AddKeyWindowDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename does already exist!.
        /// </summary>
        public static string AddKeyWindowFilenameError {
            get {
                return ResourceManager.GetString("AddKeyWindowFilenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitsize.
        /// </summary>
        public static string AddKeyWindowKeyBitSizeComboBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyBitSizeComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (email@example.com).
        /// </summary>
        public static string AddKeyWindowKeyCommentTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyCommentTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key filename.
        /// </summary>
        public static string AddKeyWindowKeyFileNameTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyFileNameTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytype.
        /// </summary>
        public static string AddKeyWindowKeyKeyTypeComboBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyKeyTypeComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password? (leave empty for none).
        /// </summary>
        public static string AddKeyWindowKeyPasswordTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyPasswordTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new SSH key.
        /// </summary>
        public static string AddKeyWindowTitle {
            get {
                return ResourceManager.GetString("AddKeyWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert ppk keys to openssh format automatically at start.
        /// </summary>
        public static string ApplicationSettingsAutoConvertText {
            get {
                return ResourceManager.GetString("ApplicationSettingsAutoConvertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettingsDescription {
            get {
                return ResourceManager.GetString("ApplicationSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit a multi-key.
        /// </summary>
        public static string ApplicationSettingsEditErrorBoxText {
            get {
                return ResourceManager.GetString("ApplicationSettingsEditErrorBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-key cannot be edited.
        /// </summary>
        public static string ApplicationSettingsEditErrorBoxTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsEditErrorBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max count of servers to save.
        /// </summary>
        public static string ApplicationSettingsMaxServers {
            get {
                return ResourceManager.GetString("ApplicationSettingsMaxServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Servers.
        /// </summary>
        public static string ApplicationSettingsSavedServers {
            get {
                return ResourceManager.GetString("ApplicationSettingsSavedServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add key to authorized_keys file of.
        /// </summary>
        public static string AuthorizedKeysAddKeyToFileOf {
            get {
                return ResourceManager.GetString("AuthorizedKeysAddKeyToFileOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content from.
        /// </summary>
        public static string AuthorizedKeysFileContentFrom {
            get {
                return ResourceManager.GetString("AuthorizedKeysFileContentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content from local machine.
        /// </summary>
        public static string AuthorizedKeysFileContentLocal {
            get {
                return ResourceManager.GetString("AuthorizedKeysFileContentLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and close.
        /// </summary>
        public static string CancelAndClose {
            get {
                return ResourceManager.GetString("CancelAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ConfirmDialogDefaultNoText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ConfirmDialogDefaultOkText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allright?.
        /// </summary>
        public static string ConfirmDialogDefaultQuestionText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to server.
        /// </summary>
        public static string ConnectToServerDescription {
            get {
                return ResourceManager.GetString("ConnectToServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to ssh://{0}@{1}.
        /// </summary>
        public static string ConnectToServerSshConnectionString {
            get {
                return ResourceManager.GetString("ConnectToServerSshConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        public static string ConnectToServerStatusBase {
            get {
                return ResourceManager.GetString("ConnectToServerStatusBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string ConnectToServerStatusFailed {
            get {
                return ResourceManager.GetString("ConnectToServerStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string ConnectToServerStatusSuccess {
            get {
                return ResourceManager.GetString("ConnectToServerStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string ConnectToServerStatusUnknown {
            get {
                return ResourceManager.GetString("ConnectToServerStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not yet tested.
        /// </summary>
        public static string ConnectToServerStatusUntested {
            get {
                return ResourceManager.GetString("ConnectToServerStatusUntested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing hostname/ip, username or password!.
        /// </summary>
        public static string ConnectToServerValidationError {
            get {
                return ResourceManager.GetString("ConnectToServerValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept connection.
        /// </summary>
        public static string ConnectWindowAcceptConnection {
            get {
                return ResourceManager.GetString("ConnectWindowAcceptConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick connect.
        /// </summary>
        public static string ConnectWindowQuickConnect {
            get {
                return ResourceManager.GetString("ConnectWindowQuickConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset values.
        /// </summary>
        public static string ConnectWindowResetValues {
            get {
                return ResourceManager.GetString("ConnectWindowResetValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string ConnectWindowTestConnection {
            get {
                return ResourceManager.GetString("ConnectWindowTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all keys.
        /// </summary>
        public static string ConnectWindowUseAllKeys {
            get {
                return ResourceManager.GetString("ConnectWindowUseAllKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use public key.
        /// </summary>
        public static string ConnectWindowUsePubKey {
            get {
                return ResourceManager.GetString("ConnectWindowUsePubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept changes and write to file.
        /// </summary>
        public static string EditKnownHostsWindowConfirmButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowConfirmButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        public static string EditKnownHostsWindowDataGridColumnHeaderFingerprintText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderFingerprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keysize.
        /// </summary>
        public static string EditKnownHostsWindowDataGridColumnHeaderKeySizeText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderKeySizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytype.
        /// </summary>
        public static string EditKnownHostsWindowDataGridColumnHeaderKeyTypeText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderKeyTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string EditKnownHostsWindowDataGridColumnHeaderOptionsText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss and Close.
        /// </summary>
        public static string EditKnownHostsWindowDismissButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDismissButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark for deletion on save.
        /// </summary>
        public static string EditKnownHostsWindowMarkForDeletionButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowMarkForDeletionButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload file and revert changes.
        /// </summary>
        public static string EditKnownHostsWindowReloadButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowReloadButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit known_hosts file.
        /// </summary>
        public static string EditKnownHostsWindowTitle {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}.
        /// </summary>
        public static string ErrorAction {
            get {
                return ResourceManager.GetString("ErrorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string ExportWindowCopyToClipboardToolTipText {
            get {
                return ResourceManager.GetString("ExportWindowCopyToClipboardToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Format.
        /// </summary>
        public static string KeyFormatDescription {
            get {
                return ResourceManager.GetString("KeyFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password.
        /// </summary>
        public static string KeysForgetPassword {
            get {
                return ResourceManager.GetString("KeysForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string KeysShowPassword {
            get {
                return ResourceManager.GetString("KeysShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password of {0}.
        /// </summary>
        public static string KeysShowPasswordOf {
            get {
                return ResourceManager.GetString("KeysShowPasswordOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SSH key.
        /// </summary>
        public static string MainWindowAddKeyToolTip {
            get {
                return ResourceManager.GetString("MainWindowAddKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected on:.
        /// </summary>
        public static string MainWindowConnectionTooltipConnectedOn {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipConnectedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currenty disconnected. Right click to open connection menu to establish a connection.
        /// </summary>
        public static string MainWindowConnectionTooltipDisconnected {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server OS:.
        /// </summary>
        public static string MainWindowConnectionTooltipServerOs {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipServerOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string MainWindowConnectMenuConnect {
            get {
                return ResourceManager.GetString("MainWindowConnectMenuConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string MainWindowConnectMenuDisconnect {
            get {
                return ResourceManager.GetString("MainWindowConnectMenuDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error converting the keyfile. See the log for details..
        /// </summary>
        public static string MainWindowConvertKeyMessageBoxErrorText {
            get {
                return ResourceManager.GetString("MainWindowConvertKeyMessageBoxErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will convert your {0}. Do you want to delete the old file?.
        /// </summary>
        public static string MainWindowConvertKeyMessageBoxText {
            get {
                return ResourceManager.GetString("MainWindowConvertKeyMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-key to a {1}-key.
        /// </summary>
        public static string MainWindowConvertKeyMessageBoxTitle {
            get {
                return ResourceManager.GetString("MainWindowConvertKeyMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to opposite format.
        /// </summary>
        public static string MainWindowConvertTooltip {
            get {
                return ResourceManager.GetString("MainWindowConvertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingCommentText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export / Delete.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingExportDeleteText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingExportDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingFingerprintText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingFingerprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keysize in bytes.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingKeySizeText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingKeySizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keytype.
        /// </summary>
        public static string MainWindowDataGridColumnHeadingKeyTypeText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingKeyTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete key from disk.
        /// </summary>
        public static string MainWindowDataGridControlsDeleteKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsDeleteKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export private key.
        /// </summary>
        public static string MainWindowDataGridControlsExportPrivateKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsExportPrivateKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export public key.
        /// </summary>
        public static string MainWindowDataGridControlsExportPublicKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsExportPublicKeyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path:.
        /// </summary>
        public static string MainWindowDataGridRowDetailsAbsolutePathText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsAbsolutePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename on disk:.
        /// </summary>
        public static string MainWindowDataGridRowDetailsFilenameText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsFilenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key filename:.
        /// </summary>
        public static string MainWindowDataGridRowDetailsPrivateKeyFilenameText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsPrivateKeyFilenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to disconnect from!.
        /// </summary>
        public static string MainWindowDisconnectBoxTextNone {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTextNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected successfully!.
        /// </summary>
        public static string MainWindowDisconnectBoxTextSuccess {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from Server.
        /// </summary>
        public static string MainWindowDisconnectBoxTitle {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit authorized_keys.
        /// </summary>
        public static string MainWindowEditAuthorizedKeys {
            get {
                return ResourceManager.GetString("MainWindowEditAuthorizedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;known_hosts&quot; file.
        /// </summary>
        public static string MainWindowEditKnownHostsFileToolTip {
            get {
                return ResourceManager.GetString("MainWindowEditKnownHostsFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string MainWindowFoundKeyPairsCountLabelPart1 {
            get {
                return ResourceManager.GetString("MainWindowFoundKeyPairsCountLabelPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keypairs in SSH directory.
        /// </summary>
        public static string MainWindowFoundKeyPairsCountLabelPart2 {
            get {
                return ResourceManager.GetString("MainWindowFoundKeyPairsCountLabelPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindowHelpMenuAbout {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question or for help.
        /// </summary>
        public static string MainWindowHelpMenuQuestion {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website/Manual.
        /// </summary>
        public static string MainWindowHelpMenuWebsite {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a server to edit the remote file!.
        /// </summary>
        public static string MainWindowIsNotRemoteTooltipText {
            get {
                return ResourceManager.GetString("MainWindowIsNotRemoteTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Format/Type:.
        /// </summary>
        public static string MainWindowKeyFormatType {
            get {
                return ResourceManager.GetString("MainWindowKeyFormatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click for help.
        /// </summary>
        public static string MainWindowRightClickHelp {
            get {
                return ResourceManager.GetString("MainWindowRightClickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click for options.
        /// </summary>
        public static string MainWindowRightClickOptions {
            get {
                return ResourceManager.GetString("MainWindowRightClickOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string MainWindowSettingsMenuAppSettings {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local user ssh config.
        /// </summary>
        public static string MainWindowSettingsMenuLocalUserSshConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuLocalUserSshConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine sshd config.
        /// </summary>
        public static string MainWindowSettingsMenuMachineSshdConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuMachineSshdConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload keys from disk.
        /// </summary>
        public static string MainWindowSettingsMenuReloadKeysFromDisk {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuReloadKeysFromDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload keys and forget passwords.
        /// </summary>
        public static string MainWindowSettingsMenuReloadKeysFromDiskAndForgetPasswords {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuReloadKeysFromDiskAndForgetPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote user ssh config.
        /// </summary>
        public static string MainWindowSettingsMenuRemoteMachineSshdConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuRemoteMachineSshdConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote machine sshd config.
        /// </summary>
        public static string MainWindowSettingsMenuRemoteUserSshConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuRemoteUserSshConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSSH GUI.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete the SSH key?.
        /// </summary>
        public static string MainWindowViewModelDeleteKeyQuestionText {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete the SSH keypair?.
        /// </summary>
        public static string MainWindowViewModelDeleteKeyQuestionTextPair {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyQuestionTextPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        public static string MainWindowViewModelDeleteKeyTitleText {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0} key: {1}.
        /// </summary>
        public static string MainWindowViewModelDynamicExportWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowViewModelDynamicExportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting keyfile!.
        /// </summary>
        public static string MainWindowViewModelExportKeyErrorMessage {
            get {
                return ResourceManager.GetString("MainWindowViewModelExportKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem loading &quot;{0}&quot;: {1}.
        /// </summary>
        public static string MainWindowViewModelProblemLoadingFileText {
            get {
                return ResourceManager.GetString("MainWindowViewModelProblemLoadingFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function is not implemented yet, but planned!.
        /// </summary>
        public static string NotImplementedBoxText {
            get {
                return ResourceManager.GetString("NotImplementedBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet.
        /// </summary>
        public static string NotImplementedBoxTitle {
            get {
                return ResourceManager.GetString("NotImplementedBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes and close.
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
    }
}
