//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSSH_GUI {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsAndTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsAndTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenSSH_GUI.StringsAndTexts", typeof(StringsAndTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AddKeyWindowAbortButtonToolTipText {
            get {
                return ResourceManager.GetString("AddKeyWindowAbortButtonToolTipText", resourceCulture);
            }
        }
        
        public static string AddKeyWindowAddKeyButtonToolTipText {
            get {
                return ResourceManager.GetString("AddKeyWindowAddKeyButtonToolTipText", resourceCulture);
            }
        }
        
        public static string AddKeyWindowKeyBitSizeComboBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyBitSizeComboBoxLabel", resourceCulture);
            }
        }
        
        public static string AddKeyWindowKeyCommentTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyCommentTextBoxLabel", resourceCulture);
            }
        }
        
        public static string AddKeyWindowKeyFileNameTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyFileNameTextBoxLabel", resourceCulture);
            }
        }
        
        public static string AddKeyWindowKeyKeyTypeComboBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyKeyTypeComboBoxLabel", resourceCulture);
            }
        }
        
        public static string AddKeyWindowKeyPasswordTextBoxLabel {
            get {
                return ResourceManager.GetString("AddKeyWindowKeyPasswordTextBoxLabel", resourceCulture);
            }
        }
        
        public static string AddKeyWindowTitle {
            get {
                return ResourceManager.GetString("AddKeyWindowTitle", resourceCulture);
            }
        }
        
        public static string ConfirmDialogDefaultNoText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultNoText", resourceCulture);
            }
        }
        
        public static string ConfirmDialogDefaultOkText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultOkText", resourceCulture);
            }
        }
        
        public static string ConfirmDialogDefaultQuestionText {
            get {
                return ResourceManager.GetString("ConfirmDialogDefaultQuestionText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowConfirmButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowConfirmButtonToolTipText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowDataGridColumnHeaderFingerprintText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderFingerprintText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowDataGridColumnHeaderKeySizeText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderKeySizeText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowDataGridColumnHeaderKeyTypeText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderKeyTypeText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowDataGridColumnHeaderOptionsText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDataGridColumnHeaderOptionsText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowDismissButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowDismissButtonToolTipText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowMarkForDeletionButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowMarkForDeletionButtonToolTipText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowReloadButtonToolTipText {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowReloadButtonToolTipText", resourceCulture);
            }
        }
        
        public static string EditKnownHostsWindowTitle {
            get {
                return ResourceManager.GetString("EditKnownHostsWindowTitle", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string ExportWindowCopyToClipboardToolTipText {
            get {
                return ResourceManager.GetString("ExportWindowCopyToClipboardToolTipText", resourceCulture);
            }
        }
        
        public static string KeyFormatDescription {
            get {
                return ResourceManager.GetString("KeyFormatDescription", resourceCulture);
            }
        }
        
        public static string MainWindowAddKeyToolTip {
            get {
                return ResourceManager.GetString("MainWindowAddKeyToolTip", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridColumnHeadingCommentText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingCommentText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridColumnHeadingExportDeleteText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingExportDeleteText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridColumnHeadingFingerprintText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingFingerprintText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridColumnHeadingKeySizeText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingKeySizeText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridColumnHeadingKeyTypeText {
            get {
                return ResourceManager.GetString("MainWindowDataGridColumnHeadingKeyTypeText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridControlsDeleteKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsDeleteKeyToolTipText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridControlsExportPrivateKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsExportPrivateKeyToolTipText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridControlsExportPublicKeyToolTipText {
            get {
                return ResourceManager.GetString("MainWindowDataGridControlsExportPublicKeyToolTipText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridRowDetailsAbsolutePathText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsAbsolutePathText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridRowDetailsFilenameText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsFilenameText", resourceCulture);
            }
        }
        
        public static string MainWindowDataGridRowDetailsPrivateKeyFilenameText {
            get {
                return ResourceManager.GetString("MainWindowDataGridRowDetailsPrivateKeyFilenameText", resourceCulture);
            }
        }
        
        public static string MainWindowEditKnownHostsFileToolTip {
            get {
                return ResourceManager.GetString("MainWindowEditKnownHostsFileToolTip", resourceCulture);
            }
        }
        
        public static string MainWindowFoundKeyPairsCountLabelPart1 {
            get {
                return ResourceManager.GetString("MainWindowFoundKeyPairsCountLabelPart1", resourceCulture);
            }
        }
        
        public static string MainWindowFoundKeyPairsCountLabelPart2 {
            get {
                return ResourceManager.GetString("MainWindowFoundKeyPairsCountLabelPart2", resourceCulture);
            }
        }
        
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelDeleteKeyQuestionText {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyQuestionText", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelDeleteKeyTitleText {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyTitleText", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelDynamicExportWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowViewModelDynamicExportWindowTitle", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelExportKeyErrorMessage {
            get {
                return ResourceManager.GetString("MainWindowViewModelExportKeyErrorMessage", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelProblemLoadingFileText {
            get {
                return ResourceManager.GetString("MainWindowViewModelProblemLoadingFileText", resourceCulture);
            }
        }
        
        public static string ApplicationSettingsDescription {
            get {
                return ResourceManager.GetString("ApplicationSettingsDescription", resourceCulture);
            }
        }
        
        public static string ApplicationSettingsMaxServers {
            get {
                return ResourceManager.GetString("ApplicationSettingsMaxServers", resourceCulture);
            }
        }
        
        public static string ApplicationSettingsAutoConvertText {
            get {
                return ResourceManager.GetString("ApplicationSettingsAutoConvertText", resourceCulture);
            }
        }
        
        public static string ApplicationSettingsSavedServers {
            get {
                return ResourceManager.GetString("ApplicationSettingsSavedServers", resourceCulture);
            }
        }
        
        public static string CancelAndClose {
            get {
                return ResourceManager.GetString("CancelAndClose", resourceCulture);
            }
        }
        
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        public static string ConnectWindowQuickConnect {
            get {
                return ResourceManager.GetString("ConnectWindowQuickConnect", resourceCulture);
            }
        }
        
        public static string ConnectWindowUsePubKey {
            get {
                return ResourceManager.GetString("ConnectWindowUsePubKey", resourceCulture);
            }
        }
        
        public static string ConnectWindowUseAllKeys {
            get {
                return ResourceManager.GetString("ConnectWindowUseAllKeys", resourceCulture);
            }
        }
        
        public static string ConnectWindowTestConnection {
            get {
                return ResourceManager.GetString("ConnectWindowTestConnection", resourceCulture);
            }
        }
        
        public static string ConnectWindowResetValues {
            get {
                return ResourceManager.GetString("ConnectWindowResetValues", resourceCulture);
            }
        }
        
        public static string ConnectWindowAcceptConnection {
            get {
                return ResourceManager.GetString("ConnectWindowAcceptConnection", resourceCulture);
            }
        }
        
        public static string AuthorizedKeysFileContentLocal {
            get {
                return ResourceManager.GetString("AuthorizedKeysFileContentLocal", resourceCulture);
            }
        }
        
        public static string AuthorizedKeysFileContentFrom {
            get {
                return ResourceManager.GetString("AuthorizedKeysFileContentFrom", resourceCulture);
            }
        }
        
        public static string AuthorizedKeysAddKeyToFileOf {
            get {
                return ResourceManager.GetString("AuthorizedKeysAddKeyToFileOf", resourceCulture);
            }
        }
        
        public static string MainWindowKeyFormatType {
            get {
                return ResourceManager.GetString("MainWindowKeyFormatType", resourceCulture);
            }
        }
        
        public static string MainWindowEditAuthorizedKeys {
            get {
                return ResourceManager.GetString("MainWindowEditAuthorizedKeys", resourceCulture);
            }
        }
        
        public static string MainWindowIsNotRemoteTooltipText {
            get {
                return ResourceManager.GetString("MainWindowIsNotRemoteTooltipText", resourceCulture);
            }
        }
        
        public static string MainWindowConnectionTooltipServerOs {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipServerOs", resourceCulture);
            }
        }
        
        public static string MainWindowConnectionTooltipConnectedOn {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipConnectedOn", resourceCulture);
            }
        }
        
        public static string MainWindowConnectionTooltipDisconnected {
            get {
                return ResourceManager.GetString("MainWindowConnectionTooltipDisconnected", resourceCulture);
            }
        }
        
        public static string MainWindowRightClickOptions {
            get {
                return ResourceManager.GetString("MainWindowRightClickOptions", resourceCulture);
            }
        }
        
        public static string MainWindowRightClickHelp {
            get {
                return ResourceManager.GetString("MainWindowRightClickHelp", resourceCulture);
            }
        }
        
        public static string AddKeyWindowDefault {
            get {
                return ResourceManager.GetString("AddKeyWindowDefault", resourceCulture);
            }
        }
        
        public static string MainWindowConvertTooltip {
            get {
                return ResourceManager.GetString("MainWindowConvertTooltip", resourceCulture);
            }
        }
        
        public static string ConnectToServerDescription {
            get {
                return ResourceManager.GetString("ConnectToServerDescription", resourceCulture);
            }
        }
        
        public static string ErrorAction {
            get {
                return ResourceManager.GetString("ErrorAction", resourceCulture);
            }
        }
        
        public static string MainWindowConvertKeyMessageBoxTitle {
            get {
                return ResourceManager.GetString("MainWindowConvertKeyMessageBoxTitle", resourceCulture);
            }
        }
        
        public static string MainWindowConvertKeyMessageBoxText {
            get {
                return ResourceManager.GetString("MainWindowConvertKeyMessageBoxText", resourceCulture);
            }
        }
        
        public static string MainWindowConvertKeyMessageBoxErrorText {
            get {
                return ResourceManager.GetString("MainWindowConvertKeyMessageBoxErrorText", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelDeleteKeyQuestionTextPair {
            get {
                return ResourceManager.GetString("MainWindowViewModelDeleteKeyQuestionTextPair", resourceCulture);
            }
        }
        
        public static string MainWindowDisconnectBoxTitle {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTitle", resourceCulture);
            }
        }
        
        public static string MainWindowDisconnectBoxTextSuccess {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTextSuccess", resourceCulture);
            }
        }
        
        public static string MainWindowDisconnectBoxTextNone {
            get {
                return ResourceManager.GetString("MainWindowDisconnectBoxTextNone", resourceCulture);
            }
        }
        
        public static string NotImplementedBoxTitle {
            get {
                return ResourceManager.GetString("NotImplementedBoxTitle", resourceCulture);
            }
        }
        
        public static string NotImplementedBoxText {
            get {
                return ResourceManager.GetString("NotImplementedBoxText", resourceCulture);
            }
        }
        
        public static string ApplicationSettingsEditErrorBoxTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsEditErrorBoxTitle", resourceCulture);
            }
        }
        
        public static string ApplicationSettingsEditErrorBoxText {
            get {
                return ResourceManager.GetString("ApplicationSettingsEditErrorBoxText", resourceCulture);
            }
        }
        
        public static string AddKeyWindowFilenameError {
            get {
                return ResourceManager.GetString("AddKeyWindowFilenameError", resourceCulture);
            }
        }
        
        public static string ConnectToServerStatusBase {
            get {
                return ResourceManager.GetString("ConnectToServerStatusBase", resourceCulture);
            }
        }
        
        public static string ConnectToServerStatusUnknown {
            get {
                return ResourceManager.GetString("ConnectToServerStatusUnknown", resourceCulture);
            }
        }
        
        public static string ConnectToServerStatusUntested {
            get {
                return ResourceManager.GetString("ConnectToServerStatusUntested", resourceCulture);
            }
        }
        
        public static string ConnectToServerStatusFailed {
            get {
                return ResourceManager.GetString("ConnectToServerStatusFailed", resourceCulture);
            }
        }
        
        public static string ConnectToServerStatusSuccess {
            get {
                return ResourceManager.GetString("ConnectToServerStatusSuccess", resourceCulture);
            }
        }
        
        public static string ConnectToServerValidationError {
            get {
                return ResourceManager.GetString("ConnectToServerValidationError", resourceCulture);
            }
        }
        
        public static string ConnectToServerSshConnectionString {
            get {
                return ResourceManager.GetString("ConnectToServerSshConnectionString", resourceCulture);
            }
        }
        
        public static string MainWindowConnectMenuConnect {
            get {
                return ResourceManager.GetString("MainWindowConnectMenuConnect", resourceCulture);
            }
        }
        
        public static string MainWindowConnectMenuDisconnect {
            get {
                return ResourceManager.GetString("MainWindowConnectMenuDisconnect", resourceCulture);
            }
        }
        
        public static string MainWindowSettingsMenuAppSettings {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuAppSettings", resourceCulture);
            }
        }
        
        public static string MainWindowSettingsMenuLocalUserSshConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuLocalUserSshConfig", resourceCulture);
            }
        }
        
        public static string MainWindowSettingsMenuMachineSshdConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuMachineSshdConfig", resourceCulture);
            }
        }
        
        public static string MainWindowSettingsMenuRemoteUserSshConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuRemoteUserSshConfig", resourceCulture);
            }
        }
        
        public static string MainWindowSettingsMenuRemoteMachineSshdConfig {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuRemoteMachineSshdConfig", resourceCulture);
            }
        }
        
        public static string MainWindowHelpMenuWebsite {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuWebsite", resourceCulture);
            }
        }
        
        public static string MainWindowHelpMenuQuestion {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuQuestion", resourceCulture);
            }
        }
        
        public static string MainWindowHelpMenuAbout {
            get {
                return ResourceManager.GetString("MainWindowHelpMenuAbout", resourceCulture);
            }
        }
        
        public static string MainWindowSettingsMenuReloadKeysFromDisk {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuReloadKeysFromDisk", resourceCulture);
            }
        }
        
        public static string MainWindowSettingsMenuReloadKeysFromDiskAndForgetPasswords {
            get {
                return ResourceManager.GetString("MainWindowSettingsMenuReloadKeysFromDiskAndForgetPasswords", resourceCulture);
            }
        }
        
        public static string KeysShowPassword {
            get {
                return ResourceManager.GetString("KeysShowPassword", resourceCulture);
            }
        }
        
        public static string KeysForgetPassword {
            get {
                return ResourceManager.GetString("KeysForgetPassword", resourceCulture);
            }
        }
        
        public static string KeysShowPasswordOf {
            get {
                return ResourceManager.GetString("KeysShowPasswordOf", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelProvidePasswordPromptHeading {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordPromptHeading", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelProvidePasswordPromptBodyHeading {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordPromptBodyHeading", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelProvidePasswordPasswordLabel {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordPasswordLabel", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelProvidePasswordErrorHeading {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordErrorHeading", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelProvidePasswordErrorContent {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordErrorContent", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelProvidePasswordButtonAbort {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordButtonAbort", resourceCulture);
            }
        }
        
        public static string MainWindowViewModelProvidePasswordButtonSubmit {
            get {
                return ResourceManager.GetString("MainWindowViewModelProvidePasswordButtonSubmit", resourceCulture);
            }
        }
    }
}
