name: staging.yml
on:
  push:
    branches:
      - 'development'
    paths:
      - 'PKGBUILD'
concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true
jobs:
  aur_publish:
    name: Update GIT AUR package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    
#    - name: Checkout
#      uses: actions/checkout@v7
#      with: 
#        ref: ${{ github.ref }}
#        fetch-depth: '1'
        
    - name: Deploy to AUR
      uses: ./.github/actions/deploy-aur
      with:
        pkgname: openssh-gui-git
        pkgbuild: openssh-gui-git/PKGBUILD
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_username: ${{ github.repository_owner }}
        commit_email: ${{ github.repository_owner }}@users.noreply.github.com
        commit_message: "Updated PKGBUILD"
        force_push: 'true'
        regenerate_srcinfo: 'true'